#
# Copyright (C) 2022 Vaticle
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

build:
  correctness:
    build:
      image: vaticle-ubuntu-21.04
      command: |
        bazel build //...
        bazel run @vaticle_dependencies//tool/checkstyle:test-coverage
        bazel test $(bazel query 'kind(checkstyle_test, //...)') --test_output=errors
    test-catalogue-of-life:
     image: vaticle-ubuntu-21.04
     command: |
       bazel run //:typedb-extractor -- dist/typedb-all-linux
       sudo systemd-run ./dist/typedb-all-linux/typedb server
       sleep 60
       bazel test //biology/catalogue_of_life:tests --test_output=errors
    test-gitapp:
      image: vaticle-ubuntu-21.04
      command: |
        bazel run //:typedb-extractor -- dist/typedb-all-linux
        sudo systemd-run ./dist/typedb-all-linux/typedb server
        sleep 60
        bazel test //software/github/tests:test-migrator-explorer --test_output=errors
    test-phone-calls-java:
      image: vaticle-ubuntu-21.04
      command: |
        bazel run //:typedb-extractor -- dist/typedb-all-linux
        sudo systemd-run ./dist/typedb-all-linux/typedb server
        sleep 60
        bazel test //telecom/phone_calls/java:test --test_output=errors
    test-phone-calls-nodejs:
      image: vaticle-ubuntu-21.04
      command: |
        bazel run //:typedb-extractor -- dist/typedb-all-linux
        sudo systemd-run ./dist/typedb-all-linux/typedb server
        sleep 60
        bazel test //telecom/phone_calls/nodejs:test --test_output=errors
    test-phone-calls-python:
      image: vaticle-ubuntu-21.04
      command: |
        pyenv global system
        bazel run //:typedb-extractor -- dist/typedb-all-linux
        sudo systemd-run ./dist/typedb-all-linux/typedb server
        sleep 60
        bazel test //telecom/phone_calls/python:test --test_output=errors
    test-xcom:
      image: vaticle-ubuntu-21.04
      command: |
        bazel run //:typedb-extractor -- dist/typedb-all-linux
        sudo systemd-run ./dist/typedb-all-linux/typedb server
        sleep 60
        bazel test //gaming/xcom:test --test_output=errors
  performance:
    test-performance-typedb-core-server:
      machine: 16-core-32-gb
      image: vaticle-ubuntu-21.04
      type: background
      timeout: "30m"
      command: |
        cat > typedb.service <<- EOM
        [Unit]
        Description=TypeDB

        [Service]
        Type=simple
        Environment=SERVER_JAVAOPTS=-Xmx16G
        ExecStart=/home/grabl/$GRABL_REPO/dist/typedb-all-linux/typedb server
        Restart=on-failure
        RestartSec=10
        KillMode=process

        [Install]
        WantedBy=multi-user.target
        EOM

        sudo mv typedb.service /etc/systemd/system/

        bazel run //:typedb-extractor-linux -- dist/typedb-all-linux
        cd ./dist/typedb-all-linux/

        sudo systemctl daemon-reload
        sudo systemctl start typedb
        export GRABL_EXPORT_PERFORMANCE_TYPEDB_CORE_URI="${HOSTNAME}:1729"
      monitor: |
        sleep 10s
        tail -f -n +1 /home/grabl/$GRABL_REPO/dist/typedb-all-linux/server/logs/typedb.log
    test-performance-typedb-core-benchmark:
      machine: 16-core-32-gb
      image: vaticle-ubuntu-21.04
      dependencies: [test-performance-typedb-core-server]
      timeout: "30m"
      command: |
        bazel run //biology/catalogue_of_life:loader -- --typedb $GRABL_EXPORT_PERFORMANCE_TYPEDB_CORE_URI
